import type { Post } from "../../lib/posts";

export const posts: Post[] = [
  {
    slug: "what-decides-gfrp-rebar-plant-economics",
    title: "What actually decides whether a GFRP rebar line makes money in India",
    summary: "The brochure lists diameter range and bars per run — the numbers that decide whether the plant pays for itself are six operating factors the brochure never mentions.",
    date: "2026-09-19",
    body: [
      { t: "p", x: "A spec sheet tells you how many bars a line runs at once and what diameter range it covers. It does not tell you whether the line makes money, because that answer sits somewhere the spec sheet never looks: how long the line takes to warm up, how much bar gets scrapped before it settles, how often you change diameter in a month, and how many people you need standing at it every shift. None of these show up in a brochure comparison, and all of them show up on the electricity bill and the material invoice by the third month of running the plant." },
      { t: "h", x: "Cold start costs you twice a day, every day" },
      { t: "p", x: "The die and the curing section need time to reach and hold their set temperature. Until they do, the bar coming off the line is out of spec — not visibly, but on the properties that matter, which is why it gets scrapped or downgraded rather than sold. That cost repeats at every cold start, and a plant running two shifts starts cold at least twice a day. Multiply the minutes lost per start by two starts and by roughly three hundred working days, and cold-start time turns out to be a bigger number than most buyers expect when they are only asking about diameter range." },
      { t: "p", x: "Time it yourself if you can, on a working line, not a demo unit that was already warm before you arrived." },
      { t: "h", x: "Startup scrap and steady-state scrap are two different numbers" },
      { t: "p", x: "Startup scrap is the material wasted while the line is still stabilizing after a cold start or a diameter change. Steady-state scrap is the rate once the line has settled and is running at speed. Suppliers sometimes quote one and let a buyer assume it covers both — it does not, and the gap between them is real fibre and resin you paid for and then paid again to dispose of. Ask for both numbers, weighed in front of you during a run, not estimated from a datasheet." },
      { t: "h", x: "Diameter changeovers are the cost nobody counts until the invoice" },
      { t: "p", x: "Most Indian plants are not running one diameter all year. A line rated for 3–20 mm bar is being asked to move across that range as orders come in, and every move means resetting the ribbing distance, re-syncing it to pulling speed, and sometimes re-tuning the die. None of that is instant. Count how many changeovers you actually run in a typical month and multiply by the time each one costs, and changeover time frequently outweighs the difference between two machines' rated running speed — the number everyone compares first." },
      { t: "h", x: "Power per kilogram, not the number on the nameplate" },
      { t: "p", x: "Connected load and actual draw are different things, and only actual draw shows up on the electricity bill. Ask for a meter reading taken during a real run, not the rated capacity from the panel. A 10 kW difference between two lines works out to roughly ₹10 lakh a year at typical industrial tariffs — enough to change which machine is actually cheaper once you run the numbers past the purchase price." },
      { t: "h", x: "Manual stations are an availability problem before they are a wage problem" },
      { t: "p", x: "Every station on a line that still needs a person standing at it — measuring, cutting, watching for slippage — is a station where output depends on someone showing up and staying trained. In most of India that is harder to solve than the wage itself: a plant running three manual stations across two shifts needs six people who know what they are doing, and losing one mid-run costs more in stopped line time than the salary difference between more and fewer manual stations ever would. Automatic cutting and synced ribbing are not conveniences — they are fewer points where the plant's output depends on someone else's Monday morning." },
      { t: "p", x: "None of these six factors appear on a spec comparison, which is exactly why they are worth asking about before the order is placed. The machine that looks cheaper on the first page is not the same question as the machine that costs less to run for the next ten years — and the second question is the one that decides whether the plant actually pays for itself." },
    ],
  },
  {
    slug: "is-18256-what-it-actually-requires-from-your-line",
    title: "IS 18256:2023: what it actually requires from your production line",
    summary: "A plain read of India's GFRP rebar standard and the stations on a production line that decide whether your bar can pass it.",
    date: "2026-09-12",
    img: { src: "/img/lab-test.jpg", alt: "Tension, flexural, and torsion test results on GFRP rebar", cap: "Lab testing · tension, flexural, torsion" },
    body: [
      { t: "p", x: "IS 18256:2023 is the Bureau of Indian Standards specification for solid round GFRP bars used in concrete reinforcement, and IS 18255:2023 sets out the test methods that go with it. Together they replaced the situation that existed before them, where every buyer wrote their own tender clause and every supplier answered it differently. BIS certification against IS 18256 is mandatory for anyone selling these bars in India, which means the ISI mark and a valid CM/L number, and that requirement does not stop at the trading company — it reaches back to the line that made the bar." },
      { t: "h", x: "What the standard is actually checking" },
      { t: "p", x: "IS 18256 sets tensile properties by bar size, minimum fibre content, bond strength, transverse shear strength, moisture absorption, and resistance to alkali exposure. None of these are cosmetic checks. A bar can look correct — right diameter, right rib pattern, right colour — and still fail every one of them, because each property comes from something that happened inside the die and the resin bath, not from what the bar looks like once it is cut and coiled." },
      { t: "h", x: "Why this is a machine question before it is a testing question" },
      { t: "p", x: "A lab report tells you whether a specific batch passed. It does not tell you whether the line that made it can pass consistently, run after run, diameter after diameter. That second question is decided upstream, at stations most buyers never ask about when they are looking at a machine." },
      { t: "p", x: "Fibre content and bond strength trace back to impregnation — whether resin reaches every filament or leaves dry fibre inside the bar, which shows up later as a void and a weak point for alkali attack. Tensile properties trace back to cure — whether the die and the curing section actually hold their set temperature through a run, because a heater that fades undercures the bar and an undercured bar does not reach its rated strength on the tensile bench, no matter what the datasheet says the line is capable of." },
      { t: "h", x: "Moisture and alkali resistance start before the resin bath" },
      { t: "p", x: "Moisture absorption and alkali resistance are two separate line items in the standard, but they start at the same place: whether the glass roving is dry before it meets resin. A line without a preheater ahead of impregnation is carrying moisture into the bar as a defect you cannot see, and cannot correct later, no matter how good the rest of the run is. This is one of the cheaper stations on a line to specify correctly and one of the most expensive to retrofit afterward." },
      { t: "h", x: "IRC:137-2022, if you are selling into highway or bridge work" },
      { t: "p", x: "Roads and bridges have a second layer on top of IS 18256: IRC:137-2022, the Indian Roads Congress guideline for designing GFRP-reinforced elements in highway projects — bridge decks, approach slabs, culverts, retaining walls. It is written in the same philosophy as ACI 440 but uses Indian material and safety-factor conventions, and it is the reference NHAI and state PWDs actually design against. If a plant's growth plan includes government road work, this is the document to read before quoting, not after a tender comes back with a clause you cannot meet." },
      { t: "p", x: "None of this changes what a line costs. It changes what question you ask before you buy one — not \"what diameter range does it run\" but \"can this line hold the temperature and the impregnation quality that IS 18256 is actually testing for, at the speed you plan to run it.\" That is a harder question to get a straight answer to, which is exactly why it is worth asking before the order, not after the first batch of bar comes back from the lab." },
    ],
  },
  {
    slug: "how-gfrp-rebar-is-made",
    title: "How GFRP rebar is actually made",
    summary: "A walk down the line from creel to cut, and what goes wrong at each station.",
    date: "2026-08-25",
    img: { src: "/img/line-overview.jpg", alt: "Full GFRP pultrusion line layout, creel to winder", cap: "The line, creel to winder" },
    body: [
      { t: "p", x: "A production line looks like one machine but it is really eight stations in a row, and each one can spoil what the previous one did. That is why a four-hour run tells you more about a machine than any specification sheet." },
      { t: "h", x: "The creel" },
      { t: "p", x: "Glass roving feeds from creels at the back of the line. How many ends you pull sets the diameter. How evenly they feed decides whether the bar has a consistent cross section, and inconsistent section is what turns into rejected batches later." },
      { t: "h", x: "Impregnation" },
      { t: "p", x: "The fibre passes through resin. On a controlled line this happens in stages rather than one bath, because dry fibre left inside a bar is a void, and voids are where alkali attack starts once the bar is in concrete." },
      { t: "h", x: "The die" },
      { t: "p", x: "Heated, and the temperature has to hold. Ask to watch the controller readout during a run rather than reading the brochure — a heater that fades above 250 °C undercures the bar, and undercured bar fails on the tensile bench." },
      { t: "h", x: "Pulling" },
      { t: "p", x: "A caterpillar puller grips along a length. A roller puller grips at points and slips. That difference shows up as elastic modulus, and modulus is what a structural engineer designs against — which is why it quietly decides which projects will accept your bar." },
    ],
  },
];
